version: '3'
services:
    web:
        container_name: web
        build:
            context: ./
            dockerfile: ./build/web/Dockerfile
            args:
                USERID: ${USERID}
                GROUPID: ${GROUPID}
                HOSTNAME: ${HOSTNAME}
        volumes:
            - ./composer:/app/.composer
            - ./www:/app/www
        ports:
            - ${HTTP_PORT}:9999
        restart: always
        depends_on:
            - mysql
    adminer:
        image: adminer
        ports:
            - ${ADMINER_PORT}:8080
        restart: always
        depends_on:
            - mysql
    mysql:
        build: ./build/db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
