version: '3'
services:
    web:
        build: ./build/web
        volumes:
            - ./build/web/default.conf:/usr/local/apache2/conf/httpd.conf
            - ./build/web/ssl:/etc/ssl
            - ./www:/var/www/html
        ports:
            - ${HTTP_PORT}:80
            - ${HTTPS_PORT}:443
        environment:
            - WEB_HOST=${WEB_HOST}
        restart: always
        depends_on:
            - php-fpm
            - mysql
    php-fpm:
        build: ./build/php-fpm
        restart: always
        volumes:
            - ./www:/var/www/html
    php-cli:
        build: ./build/php-cli
        volumes:
            - ./www:/var/www/html
    adminer:
        image: adminer
        ports:
            - ${ADMINER_PORT}:8080
        restart: always
        depends_on:
            - mysql
    mysql:
        build: ./build/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
